I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 56, in script
    if g == false and d == false:
  File "game/script.rpy", line 56, in <module>
    if g == false and d == false:
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 56, in script
    if g == false and d == false:
  File "renpy/ast.py", line 1852, in execute
    if renpy.python.py_eval(condition):
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 56, in <module>
    if g == false and d == false:
NameError: name 'false' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.2.1292
Swan 1.0
Wed Jun 23 17:59:48 2021
